import { Router } from 'express';
import { randomUUID } from 'crypto';
import { requireJWT, requireRole } from '../middleware/auth.js';

export function createEnterpriseRouter(db) {
    const router = Router();

    // Utility to get current timestamp
    const now = () => Date.now();

    /**
     * POST /enterprise/register
     * Registers a new Enterprise Client.
     * Expected body: { companyName, walletAddress, planType }
     */
    router.post('/register', (req, res) => {
        try {
            const { companyName, walletAddress, planType } = req.body;

            if (!companyName || !walletAddress) {
                return res.status(400).json({ ok: false, error: "companyName and walletAddress are required" });
            }

            const activePlan = planType || "BASIC";
            let ratePerOp = 0.002;
            let monthlyMin = 1000;

            if (activePlan === "PRO") {
                ratePerOp = 0.005;
                monthlyMin = 5000;
            } else if (activePlan === "ENTERPRISE") {
                ratePerOp = 0.01;
                monthlyMin = 20000;
            }

            const clientId = randomUUID();

            db.prepare(`
                INSERT INTO enterprise_clients (
                    client_id, company_name, wallet_address, plan_type, 
                    rate_per_op, monthly_minimum, deposit_balance, status, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            `).run(clientId, companyName, walletAddress, activePlan, ratePerOp, monthlyMin, 0, 'ACTIVE', now());

            const apiKey = 'sk_ent_' + randomUUID().replace(/-/g, '');
            db.prepare(`
                INSERT INTO enterprise_api_keys (api_key, client_id, created_at)
                VALUES (?, ?, ?)
            `).run(apiKey, clientId, now());

            res.status(200).json({
                ok: true,
                client: {
                    clientId,
                    companyName,
                    walletAddress,
                    planType: activePlan,
                    ratePerOp,
                    monthlyMinimum: monthlyMin,
                    status: 'ACTIVE'
                },
                apiKey // Only show once
            });
        } catch (error) {
            console.error("[EnterpriseRegister]", error);
            res.status(500).json({ ok: false, error: "Internal server error" });
        }
    });

    /**
     * Middleware to authenticate enterprise API via JWT
     */
    const requireEnterprise = [requireJWT, requireRole('enterprise'), (req, res, next) => {
        const client = db.prepare(`SELECT * FROM enterprise_clients WHERE wallet_address = ?`).get(req.user.wallet);
        if (!client) {
            return res.status(401).json({ ok: false, error: "Enterprise Client not found" });
        }

        if (client.status !== 'ACTIVE') {
            return res.status(403).json({ ok: false, error: "Client suspended or inactive" });
        }

        req.enterprise = client;
        next();
    }];

    /**
     * GET /enterprise/billing
     * Returns current balance and billing details for the authenticated enterprise.
     */
    router.get('/billing', requireEnterprise, (req, res) => {
        res.status(200).json({
            ok: true,
            billing: {
                clientId: req.enterprise.client_id,
                planType: req.enterprise.plan_type,
                depositBalance: req.enterprise.deposit_balance,
                ratePerOp: req.enterprise.rate_per_op,
                monthlyMinimum: req.enterprise.monthly_minimum
            }
        });
    });

    /**
     * GET /enterprise/usage
     * Returns ops usage for the authenticated client.
     */
    router.get('/usage', requireEnterprise, (req, res) => {
        try {
            // Summary of ops based on revenue events generated by this client
            const usage = db.prepare(`
                SELECT source as opType, COUNT(*) as count, SUM(amount) as cost
                FROM revenue_events
                WHERE enterprise_id = ?
                GROUP BY source
            `).all(req.enterprise.client_id);

            const totalCost = usage.reduce((sum, row) => sum + row.cost, 0);

            res.status(200).json({
                ok: true,
                usage,
                totalCost,
                depositBalance: req.enterprise.deposit_balance
            });
        } catch (error) {
            console.error("[EnterpriseUsage]", error);
            res.status(500).json({ ok: false, error: "Internal server error" });
        }
    });

    /**
     * POST /enterprise/deposit
     * Notify backend of deposit (primarily used for off-chain testing or receipt mapping)
     * Real deposit balance increment happens via indexing RevenueVault deposits.
     */
    router.post('/deposit', requireEnterprise, (req, res) => {
        const { txHash, amount } = req.body;

        try {
            // For the sake of the simulator, we will credit the balance directly here
            // In a strict production environment, this is only done by deposit_detector.js
            const currentBalance = req.enterprise.deposit_balance;
            const newBalance = currentBalance + Number(amount);

            db.prepare(`
                UPDATE enterprise_clients 
                SET deposit_balance = ? 
                WHERE client_id = ?
            `).run(newBalance, req.enterprise.client_id);

            res.status(200).json({
                ok: true,
                message: "Deposit processed.",
                newBalance,
                txHash
            });
        } catch (error) {
            console.error("[EnterpriseDeposit]", error);
            res.status(500).json({ ok: false, error: "Internal server error" });
        }
    });

    return router;
}

export function createDemandMetricsRouter(db) {
    const router = Router();

    // We can protect this with requireAdminKey upstream
    router.use((req, res, next) => {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Admin-Key, X-Enterprise-Key");
        if (req.method === 'OPTIONS') {
            return res.sendStatus(200);
        }
        next();
    });

    router.get('/metrics', (req, res) => {
        try {
            const stats = db.prepare(`
                SELECT 
                    SUM(deposit_balance) as total_enterprise_balance,
                    COUNT(client_id) as active_clients
                FROM enterprise_clients
                WHERE status = 'ACTIVE'
            `).get();

            // Total revenue from events in last 24h
            const oneDayAgo = Date.now() - 24 * 60 * 60 * 1000;
            const revStats = db.prepare(`
                SELECT 
                    COUNT(*) as ops_last_24h,
                    SUM(amount) as revenue_last_24h
                FROM revenue_events
                WHERE created_at > ?
            `).get(oneDayAgo);

            const opsGrouped = db.prepare(`
                SELECT source, COUNT(*) as count, SUM(amount) as revenue
                FROM revenue_events
                GROUP BY source
            `).all();

            res.status(200).json({
                ok: true,
                data: {
                    total_enterprise_balance: stats.total_enterprise_balance || 0,
                    active_clients: stats.active_clients || 0,
                    ops_last_24h: revStats.ops_last_24h || 0,
                    revenue_last_24h: revStats.revenue_last_24h || 0,
                    ops_grouped: opsGrouped
                }
            });
        } catch (error) {
            console.error("[DemandMetrics]", error);
            res.status(500).json({ ok: false, error: "Internal server error" });
        }
    });

    return router;
}
