import { MarketingLayout } from "@/components/layout/MarketingLayout";
import { SectionContainer } from "@/components/ui/SectionContainer";
import { TrendingUp, BarChart3, LineChart } from "lucide-react";

export default function InvestorsPage() {
    return (
        <MarketingLayout>
            <SectionContainer className="pt-32">
                <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">Investment Thesis</h1>
                <p className="text-xl text-muted mb-12 max-w-3xl">
                    An overview of the Satelink protocol economics, sustainable yield generation, and the shift from "emissions-first" to "revenue-first" token design.
                </p>

                <div className="mb-20">
                    <h2 className="text-3xl font-bold text-white mb-6 border-b border-border pb-4">The Market Problem</h2>
                    <p className="text-xl text-zinc-400 leading-relaxed max-w-4xl">
                        Legacy decentralized infrastructure providers bootstrap supply by offering nodes massive token rewards drawn from protocol inflation. This artificially subsidizes compute costs, leading to an illusion of product-market-fit. When the core protocol runs out of tokens to distribute, node runners inevitably dump their holdings and abandon the network.
                    </p>
                </div>

                <div className="grid md:grid-cols-2 gap-8 mb-20">
                    <div className="p-8 bg-surface border border-emerald-500/20 rounded-2xl">
                        <TrendingUp className="w-10 h-10 text-emerald-400 mb-6" />
                        <h3 className="text-2xl font-bold text-white mb-4">Revenue-Backed Model</h3>
                        <p className="text-zinc-400 leading-relaxed mb-6">
                            Satelink operates fundamentally like a standard B2B SaaS business mapped onto a decentralized topology. Enterprise customers pay fixed architectural fees generated by real-world usage. 50% of this real revenue distributes back to nodes providing the verifiable computation.
                        </p>
                        <ul className="space-y-2 text-zinc-300">
                            <li>✓ <strong>Sustainable Economics:</strong> Organic token utility directly tied to network traction.</li>
                            <li>✓ <strong>Transparent Splits:</strong> Cryptographically verifiable treasury distributions.</li>
                        </ul>
                    </div>

                    <div className="p-8 bg-surface border border-blue-500/20 rounded-2xl">
                        <LineChart className="w-10 h-10 text-blue-400 mb-6" />
                        <h3 className="text-2xl font-bold text-white mb-4">No Emission Dependency</h3>
                        <p className="text-zinc-400 leading-relaxed mb-6">
                            Instead of infinite token inflation, our unit economics calculate profitability based purely on transaction volume against infrastructure overhead.
                        </p>
                        <p className="text-zinc-400 leading-relaxed">
                            If the network generates <strong>zero volume</strong>, node operators correctly earn <strong>zero rewards</strong>, allowing natural supply contraction. There is no artificial bootstrapping inflation.
                        </p>
                    </div>
                </div>

                <div className="p-10 bg-card border border-border rounded-3xl text-center max-w-3xl mx-auto">
                    <BarChart3 className="w-12 h-12 text-blue-500 mx-auto mb-6" />
                    <h2 className="text-3xl font-bold text-white mb-4">Long-Term Infrastructure Thesis</h2>
                    <p className="text-zinc-400 mb-8 leading-relaxed">
                        By eliminating the legacy inflationary subsidy mechanism, Satelink is the first verifiable infrastructure network possessing the economic durability required to outlast transient market cycles.
                    </p>
                    <a href="mailto:investors@satelink.network" className="inline-block px-8 py-3 bg-white text-black font-semibold rounded-xl hover:bg-zinc-200 transition-colors">
                        Contact Investor Relations
                    </a>
                </div>
            </SectionContainer>
        </MarketingLayout>
    );
}
